language: csharp
solution: EnglishWords.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore EnglishWords.sln
after_script:
  - nunit-console EnglishWords.Test/bin/Release/SimpleCacheWrapper.Test.dll